# Generated by Django 4.2.27 on 2026-01-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_classes_person_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='year',
            field=models.IntegerField(),
        ),
    ]
